### ISSUE TITLE
[Doc Request] Getting started documentation

### ISSUE THREAD

**Issue by adelowo** [datumforge/datum#1072]
Hi all, 

Interesting project, I took a Quick Look at the repo yesterday and tried to set it up locally 
to probably work on an issue or see how I can be helpful in my free time but I couldn't seem to 
get it working.

I had limited time to take a look but I suppose I should be able to get it up and running over the weekend 
when I have more free time but it'd be great if there was a ___getting started___ guide.

```
task install && task generate
```

seems to error out 

![CleanShot 2024-06-28 at 16 11 57](https://github.com/datumforge/datum/assets/12677701/24abc97e-c67a-4a51-b606-473f8abccfff)

**Comment by matoszz** [comment]
hey @adelowo thanks for your comment / request; you're totally right, we're a bit sparse on the local setup guide. I was actually just looking at a project called Hermit https://github.com/cashapp/hermit that seemed like maybe a good way to get our local dependencies bookstrapped into the repo. It appears there's also an un-related error from the local setup from your screen shot around possibly an upstream openFGA change so @golanglemonade is going to look at that as well. Appreciate any support / help you're willing to provide!

**Comment by adelowo** [comment]
> hey @adelowo thanks for your comment / request; you're totally right, we're a bit sparse on the local setup guide. I was actually just looking at a project called Hermit https://github.com/cashapp/hermit that seemed like maybe a good way to get our local dependencies bookstrapped into the repo. It appears there's also an un-related error from the local setup from your screen shot around possibly an upstream openFGA change so @golanglemonade is going to look at that as well. Appreciate any support / help you're willing to provide!

thanks! Will checkout hermit

**Comment by golanglemonade** [comment]
@adelowo The latest release should resolve the error you were seeing with `task generate`. Thanks for reporting it!

**Comment by adelowo** [comment]
> @adelowo The latest release should resolve the error you were seeing with `task generate`. Thanks for reporting it!

works perfectly. thanks!
