### ISSUE TITLE
Performance test + validate turso multi-tenancy

### ISSUE THREAD

**Issue by matoszz** [datumforge/datum#118]
We have an idea that this system could be run in such a way where we create a SQLLite database via Turso for every Organization (or create a paid-tier feature which allows for this)and take advantage of Turso's advertised [multitenancy](https://turso.tech/multitenancy). We need to validate latency of requests, cost(s) associated, etc., as a part of vetting this. Additionally we need to build in the underlying capability to test it at all, so a portion of this issue is verifying the code / constructs written; we need to add:
- viper command flag to create / initialize a new database + schema for every org created
- code hooks to create / launch this database
- tests to ensure multi-database driver functions
- turso sdk / client integration, internal schema fields to store / reference ID's

**Comment by golanglemonade** [comment]
this is all setup except the management of the clients. However, we've decided to go with Postgres for now, with possible solutions on single-tenancy db options but with postgres, so closing this one out.
