### ISSUE TITLE
Implement ability to receive API tokens for authentication

### ISSUE THREAD

**Issue by matoszz** [datumforge/datum#277]
- tokens should require a user to set an expiration
- tokens should have specific abilities which can be set (e.g. read all, modify organization, modify billing, etc.) - this may require decisions / implementations on other parts of the stack but the evaluation of the ability before the mutation is accepted should be enough to work off of
- tokens should have method(s) of only displaying once and then only being referred to via the derivedkeys setup within this repo
- tokens should be scoped to some top level domain (e.g. organizations) but likely not work _across_ organizations for sanity and blast radius (a different kind of token may be a better idea for this)

**Comment by golanglemonade** [comment]
Created https://github.com/datumforge/datum/issues/914 which is the remaining work around API tokens.
