### ISSUE TITLE
Add Redis client libraries / interface for KV storage

### ISSUE THREAD

**Issue by matoszz** [datumforge/datum#287]
We have several needs for a key value store, especially one which can manage ongoing state for the application  - Redis is the maintainers current preference.

- Add the golang redis client libraries / init interface into the data store
- add relevant compose, tasks, local development utilities

At the time of writing, the echo server's ratelimiterstore could leverage the KV implementation, and passkeys are targeted as well; ideally migrate anything already implemented over to this new setup

**Comment by golanglemonade** [comment]
Redis client was added and should be able to be leveraged by the rate limiter middleware now: https://github.com/datumforge/datum/blob/main/internal/cache/client.go
