### ISSUE TITLE
Investigate flakey user tests

### ISSUE THREAD

**Issue by tylerauerbeck** [datumforge/datum#377]
We've seen a handful of occasions (on different tests with the `TestMutation_CreateUser` test where the test(s) will fail with `personal org expected to be created`. We should investigate what's causing these tests to flake and get that addressed. See example below:

```
FAIL: TestMutation_CreateUser (0.08s)
    --- FAIL: TestMutation_CreateUser/Create_no_display_name,_should_default_to_email (0.01s)
        user_test.go:261:
            	Error Trace:	/workdir/internal/graphapi/user_test.go:261
            	Error:      	Should be true
            	Test:       	TestMutation_CreateUser/Create_no_display_name,_should_default_to_email
            	Messages:   	personal org expected to be created
FAIL
```

**Comment by golanglemonade** [comment]
I haven't seen this in a few days, when it used to fail frequently. I believe the test update in the linked PR fixed this.
