### ISSUE TITLE
Cleanup constraint errors in the graphql resolvers

### ISSUE THREAD

**Issue by golanglemonade** [datumforge/datum#415]
Right now we check to see if an error is a constraint error, e,g: 

```
	if generated.IsConstraintError(err) {
			constraintError := err.(*generated.ConstraintError)

			r.logger.Debugw("constraint error", "error", constraintError.Error())

			return nil, constraintError
		}
```

But we don't make that a better error for the user so the response looks like 
```
Error: {"networkErrors":null,"graphqlErrors":[{"message":"generated: constraint failed: FOREIGN KEY constraint failed","path":["createOrgMembership"]}]}
```

We should instead parse this and return a more user friendly error.

**Comment by matoszz** [comment]
In case it's helpful, I already played around a bit with returning more user friendly errors here: https://github.com/datumforge/datum/blob/main/internal/httpserve/middleware/auth/errors.go#L38

**Comment by golanglemonade** [comment]
@Zeklin fyi, this logic was all centralized here now for all resovlers: https://github.com/datumforge/datum/blob/main/internal/graphapi/errors.go#L76
