### ISSUE TITLE
Exploratory investigation of LibSQL / SQLite with OpenFGA

### ISSUE THREAD

**Issue by matoszz** [datumforge/datum#705]
In general we want less state machines. We today already have Redis, SQLite, PostgreSQL, and will likely have more in the future. In an effort to consolidate the data interfaces we use, we should investigate the effort associated with contributing the necessary drivers (or creating a shim) to use LibSQL or SQLite with the OpenFGA project.

**Comment by golanglemonade** [comment]
Relates to: https://github.com/openfga/roadmap/issues/56

**Comment by golanglemonade** [comment]
We are planning on using psql for now so closing this out. There are issues in openfga (linked above) that would need to be completed in order to enable additional drivers to be submitted to the project.
