### ISSUE TITLE
Evaluate KraftCloud as possible target deployment environment

### ISSUE THREAD

**Issue by matoszz** [datumforge/datum#706]
KraftCloud is currently in public beta, but has some very appealing features (e.g. lower footprint / compute utilization, faster launch times, simplier constructs, and built on Equinix Metal) we'd like to explore. Perform a time-box evaluation of the service and write up findings.

**Comment by golanglemonade** [comment]
Branches: 
- Datum: https://github.com/datumforge/datum/compare/KC?expand=1
- OpenFGA: https://github.com/golanglemonade/openfga/pull/1/files
